---
- hosts: localhost
  become: yes

  # Variables in the file:
  # user - the user of the machine
  # dotfiles_repo - git repo of the config files
  # dotfiles_dir - destination of the config files
  vars_files:
    - vars.yml

  tasks:

    - name: Install system variables.
      tags: install
      ansible.builtin.package:
        name:
          - neovim
          - docker
          - "python3-docker-compose"
          - terraform
          - vagrant
          - podman
          - nodejs
          - stow
          - go
          - "go-doc"
          - fish
          - htop
        state: latest

    - name: Download SpaceVIM
      get_url:
        dest: /home/{{ user }}
        url: https://spacevim.org/install.sh
        owner: "{{ user }}"
        mode: 0744

    - name: Install SpaceVIM
      shell: >
        cd /home/{{ user }};
        ./install.sh
        # rm install.sh
      become: no

    - name: Make sure Docker was started and enabled.
      service:
        name: docker
        state: started
        enabled: yes

    # ________________________________________
    # Setting configuration files from git repo
    - stat: path={{ dotfiles_dir }}
      register: dot_file
      tags: conf

    - name: Check out dotFiles from repository.
      git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
      delegate_to: localhost
      run_once: true
      become: no
      when: dot_file.stat.exists == false
      tags: conf

 
    # To apply all settings through stow should remove 'n' argument
    # Otherwise just comment the block below
    - name: Apply config files
      shell: >
        # cd /home/{{ user }};
        # touch .bash_aliases;
        # mkdir /home/{{ user }}/notes;
        cd {{ dotfiles_dir }};
        stow -vSt ~ bash fish note spacevim;
        source /home/{{ user }}/.bash_aliases
      become: no
      register: shellCommand
      tags: conf
    # ________________________________________
